### ISSUE TITLE
Helm Installation

### ISSUE THREAD

**Issue by albertnanda** [Hydrospheredata/hydro-serving-helm#3]
Hi, 
NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE       SELECTOR
docker-registry-ml-lambda         ClusterIP   10.100.122.153   <none>        5000/TCP                     24s       app=docker-registry,release=ml-lambda
elasticsearch-ml-lambda           ClusterIP   10.100.169.178   <none>        9200/TCP                     24s       app=elasticsearch,release=ml-lambda
hydro-serving-gateway-ml-lambda   ClusterIP   10.100.42.231    <none>        9090/TCP,9091/TCP            24s       app=gateway,release=ml-lambda
hydro-serving-manager-ml-lambda   ClusterIP   10.100.205.87    <none>        9090/TCP,9091/TCP            24s       app=manager,release=ml-lambda
hydro-serving-sidecar-ml-lambda   ClusterIP   10.100.76.101    <none>        8080/TCP,8081/TCP,8082/TCP   24s       app=sidecar,release=ml-lambda
hydro-serving-ui-ml-lambda        ClusterIP   10.100.97.142    <none>        9091/TCP                     24s       app=ui,release=ml-lambda
influx-ml-lambda                  ClusterIP   10.100.88.22     <none>        8086/TCP                     24s       app=influx,release=ml-lambda
kubernetes                        ClusterIP   10.100.0.1       <none>        443/TCP                      37m       <none>
postgres-ml-lambda                ClusterIP   10.100.205.26    <none>        5432/TCP                     24s       app=postgres,release=ml-lambda

And http://localhost is not working.

Thanks,
AN

**Comment by tidylobster** [comment]
Hi, @albertnanda 
Sorry, that's the missing part. You should also port-forward (or expose) your deployment. I will add that in the next documentation release. 

```
$ kubectl port-forward deploy/ml-lambda-sidecar 8080:80
```
