### ISSUE TITLE
AWS EKS ALB installation attempt

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving-helm#4]
Hi,

   We are trying to install MlLambda on AWS EKS and expose the 'sidecar' to an Application LoadBalancer (ALB). 
 So using the Helm charts - to set the annotations and  enable ingress.

![chart-name-error](https://user-images.githubusercontent.com/45240898/53771967-a41d5f80-3eb2-11e9-9eb3-2316601d0545.PNG)

When I try to install as shown in the image above- I get this error. It might be a Helm issue outside your purview - but if you can assist us it will hasten our adoption process of Hydrosphere and expand its usage. 

We have had no issues with 
1. Direct install using the Helm charts provided and accessing the sidecar using the port forward mechanism. 

For larger coverage - exposing it to ALB provides a larger umbrella of usage for us.

Thanks,

Ravi

"Text of the commands used in the image"

```
ubuntu@ip-12---218:~/hydro-serving-helm$  helm install --name my-release hydro-serving/serving \
>   --set sidecar.ingress.enabled=true \
>   --set sidecar.ingress.annotations={kubernetes.io/ingress.class: alb,alb.ingress.kubernetes.io/scheme: internet-facing} 
**Error: This command needs 1 argument: chart name**
```

**Comment by kmakarychev-dev** [comment]
Hi @ravimadhusudhan8,

You should put arguments with spaces into quotes:
```
--set "sidecar.ingress.annotations={kubernetes.io/ingress.class: alb,alb.ingress.kubernetes.io/scheme: internet-facing}"
```

Btw, you cannot pass maps in this way. You should pass each annotation as a separate value. Try something like this:
```
helm install --name my-release hydro-serving/serving \
--set sidecar.ingress.enabled=true \
--set sidecar.ingress.annotations."kubernetes\.io/ingress\.class"=alb \
--set sidecar.ingress.annotations."alb\.ingress\.kubernetes\.io/scheme"=internet-facing
```

**Comment by ravimadhusudhan8** [comment]
Thanks @mkf-simpson that worked - installation wise.
